// Generated by CoffeeScript 2.7.0
(function() {
  var indexOf = [].indexOf;

  exports.json2csv = function(inp, args, ctx, cb) {
    var f, fields, i, j, k, l, len, len1, len2, m, row, rows, v;
    fields = [];
// First pass to get fields
    for (j = 0, len = inp.length; j < len; j++) {
      i = inp[j];
      for (k in i) {
        v = i[k];
        if (indexOf.call(fields, k) < 0) {
          fields.push(k);
        }
      }
    }
    // Second pass to make rows
    rows = [];
    for (l = 0, len1 = inp.length; l < len1; l++) {
      i = inp[l];
      row = [];
      for (m = 0, len2 = fields.length; m < len2; m++) {
        f = fields[m];
        row.push(JSON.stringify(i[f]));
      }
      rows.push(row.join(','));
    }
    // Add fields header and join them together
    rows.unshift(fields);
    return cb(null, rows.join('\n'));
  };

}).call(this);
