// Generated by CoffeeScript 1.11.1
(function() {
  var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  exports.json2csv = function(inp, args, ctx, cb) {
    var f, fields, i, j, k, l, len, len1, len2, m, row, rows, v;
    fields = [];
    for (j = 0, len = inp.length; j < len; j++) {
      i = inp[j];
      for (k in i) {
        v = i[k];
        if (indexOf.call(fields, k) < 0) {
          fields.push(k);
        }
      }
    }
    rows = [];
    for (l = 0, len1 = inp.length; l < len1; l++) {
      i = inp[l];
      row = [];
      for (m = 0, len2 = fields.length; m < len2; m++) {
        f = fields[m];
        row.push(JSON.stringify(i[f]));
      }
      rows.push(row.join(','));
    }
    rows.unshift(fields);
    return cb(null, rows.join('\n'));
  };

}).call(this);
