// Generated by CoffeeScript 1.8.0
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  exports.json2csv = function(inp, args, ctx, cb) {
    var f, fields, i, k, row, rows, v, _i, _j, _k, _len, _len1, _len2;
    fields = [];
    for (_i = 0, _len = inp.length; _i < _len; _i++) {
      i = inp[_i];
      for (k in i) {
        v = i[k];
        if (__indexOf.call(fields, k) < 0) {
          fields.push(k);
        }
      }
    }
    rows = [];
    for (_j = 0, _len1 = inp.length; _j < _len1; _j++) {
      i = inp[_j];
      row = [];
      for (_k = 0, _len2 = fields.length; _k < _len2; _k++) {
        f = fields[_k];
        row.push(JSON.stringify(i[f]));
      }
      rows.push(row.join(','));
    }
    rows.unshift(fields);
    return cb(null, rows.join('\n'));
  };

}).call(this);
