// Generated by CoffeeScript 1.8.0
(function() {
  exports.atob = function(inp, args, ctx, cb) {
    var tob;
    tob = new Buffer(inp, 'base64').toString('binary');
    return cb(null, tob);
  };

  exports.btoa = function(inp, args, ctx, cb) {
    var buffer, toa;
    buffer = null;
    if (inp instanceof Buffer) {
      buffer = inp;
    } else {
      buffer = new Buffer(inp.toString(), 'binary');
    }
    toa = buffer.toString('base64');
    return cb(null, toa);
  };

}).call(this);
