// Generated by CoffeeScript 1.11.1
(function() {
  var exec, known_exec, known_spawn, ref, spawn;

  ref = require('child_process'), exec = ref.exec, spawn = ref.spawn;

  known_exec = 'cp'.split(' ');

  known_spawn = 'vim tmux th coffee node pm2 npm git make'.split(' ');

  known_exec.map(function(k) {
    return exports[k] = function(inp, args, ctx, cb) {
      return exec([k].concat(args).join(' '), function(err, stdout, stderr) {
        return cb(null, stdout);
      });
    };
  });

  known_spawn.map(function(k) {
    return exports[k] = function(inp, args, ctx, cb) {
      var child;
      process.stdin.setRawMode(false);
      ctx._readline.pause();
      child = spawn(k, args, {
        stdio: 'inherit'
      });
      return child.on('exit', function(e, code) {
        process.stdin.setRawMode(true);
        ctx._readline.prompt();
        return cb(null, 'Exited: ' + k);
      });
    };
  });

  exports.exec = function(inp, args, ctx, cb) {
    return exec(args[0], function(err, stdout, stderr) {
      return cb(null, stdout);
    });
  };

}).call(this);
