// Generated by CoffeeScript 1.8.0
(function() {
  var exec;

  exec = require('child_process').exec;

  exports.exec = function(inp, args, ctx, cb) {
    return exec(args[0], function(err, stdout, stderr) {
      return cb(null, stdout);
    });
  };

}).call(this);
