// Generated by CoffeeScript 1.8.0
(function() {
  var make_histogram, make_padding, padded;

  padded = function(s, n) {
    if (n == null) {
      n = 40;
    }
    return make_padding(n - s.length) + s;
  };

  make_padding = function(n) {
    var i;
    return ((function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; 0 <= n ? _i <= n : _i >= n; i = 0 <= n ? ++_i : --_i) {
        _results.push(' ');
      }
      return _results;
    })()).join('');
  };

  make_histogram = function(l, x) {
    var i, n, r, rows, _i, _j, _len, _ref;
    if (x == null) {
      x = '#';
    }
    rows = [];
    for (_i = 0, _len = l.length; _i < _len; _i++) {
      n = l[_i];
      if (typeof n === 'object') {
        r = padded(n.item + ' ');
        n = n.count;
      } else {
        r = '';
      }
      for (i = _j = 0, _ref = n - 1; 0 <= _ref ? _j <= _ref : _j >= _ref; i = 0 <= _ref ? ++_j : --_j) {
        r += x;
      }
      rows.push(r);
    }
    return rows.join('\n');
  };

  exports.histogram = function(inp, args, ctx, cb) {
    return cb(null, make_histogram(inp || args[0]));
  };

}).call(this);
