// Generated by CoffeeScript 1.11.1
(function() {
  var make_histogram, make_padding, padded;

  padded = function(s, n) {
    if (n == null) {
      n = 40;
    }
    return make_padding(n - s.length) + s;
  };

  make_padding = function(n) {
    var i;
    return ((function() {
      var j, ref, results;
      results = [];
      for (i = j = 0, ref = n; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        results.push(' ');
      }
      return results;
    })()).join('');
  };

  make_histogram = function(l, x) {
    var i, j, k, len, n, r, ref, rows;
    if (x == null) {
      x = '#';
    }
    rows = [];
    for (j = 0, len = l.length; j < len; j++) {
      n = l[j];
      if (typeof n === 'object') {
        r = padded(n.item + ' ');
        n = n.count;
      } else {
        r = '';
      }
      for (i = k = 0, ref = n - 1; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
        r += x;
      }
      rows.push(r);
    }
    return rows.join('\n');
  };

  exports.histogram = function(inp, args, ctx, cb) {
    return cb(null, make_histogram(inp || args[0]));
  };

}).call(this);
