// Generated by CoffeeScript 1.11.1
(function() {
  var jquery, jsdom;

  jsdom = require('jsdom');

  jquery = require('jquery');

  exports.html2text = function(inp, args, ctx, cb) {
    return jsdom.env(inp, function(err, window) {
      var $, text;
      $ = jquery(window);
      text = $('h1, h2, h3, p').map(function() {
        return $(this).text();
      }).get().join(' ... ');
      return cb(null, text);
    });
  };

  exports.jq = function(inp, args, ctx, cb) {
    return jsdom.env(inp, function(err, window) {
      var $, els;
      $ = jquery(window);
      els = [];
      $(args.join(' ')).each(function() {
        var $el, attr, el_json, i, len, ref;
        $el = $(this);
        el_json = {
          text: $el.text()
        };
        ref = this.attributes;
        for (i = 0, len = ref.length; i < len; i++) {
          attr = ref[i];
          el_json[attr.name] = attr.value;
        }
        return els.push(el_json);
      });
      return cb(null, els);
    });
  };

}).call(this);
