// Generated by CoffeeScript 2.7.0
(function() {
  // HTTP Requests
  var _, _parseResponseData, _parseResponseHeaders, fixUrl, httpMethod, parseResponseAll, parseResponseData, parseResponseHeaders, request, url;

  request = require('request').defaults({
    encoding: null
  });

  url = require('url');

  _ = require('underscore');

  // Response parsers
  _parseResponseData = function(res, data) {
    var e;
    if (data instanceof Buffer || typeof data === 'string') {
      try {
        data = JSON.parse(data);
      } catch (error) {
        e = error;
        if (data instanceof Buffer) {
          data = data.toString();
        }
      }
    }
    return data;
  };

  parseResponseData = function(cb) {
    return function(err, res, data) {
      return cb(err, _parseResponseData(res, data));
    };
  };

  _parseResponseHeaders = function(res, data) {
    return res.headers;
  };

  parseResponseHeaders = function(cb) {
    return function(err, res, data) {
      return cb(err, _parseResponseHeaders(res, data));
    };
  };

  parseResponseAll = function(cb) {
    return function(err, res, data) {
      return cb(err, {
        data: _parseResponseData(res, data),
        headers: _parseResponseHeaders(res, data)
      });
    };
  };

  // Abstract http method using given response parser

  // METHOD url {query} {auth, headers}
  fixUrl = function(u) {
    if (url.parse(u).protocol == null) {
      return 'http://' + u;
    } else {
      return u;
    }
  };

  httpMethod = function(method, responseParser = parseResponseData) {
    return function(inp, args, ctx, cb) {
      var auth, headers, req, request_options;
      ({headers, auth} = args[2] || {});
      request_options = {
        url: fixUrl(args[0]),
        method: method,
        json: (inp == null) || (typeof inp === 'object'),
        body: method !== 'GET' ? inp : void 0,
        qs: method === 'GET' ? args[1] : void 0,
        headers: _.extend({
          'user-agent': 'Hashpipe HTTP Module'
        }, headers)
      };
      req = request(request_options, responseParser(cb));
      // The multipart way
      // req_data = req.form()
      // req_data.append k, v for k, v of inp
      if (auth) {
        return req.auth(auth.username, auth.password);
      }
    };
  };

  // get "url" -> {data} / "html"
  exports.get = httpMethod('GET');

  exports['get-headers'] = httpMethod('GET', parseResponseHeaders);

  exports['get-all'] = httpMethod('GET', parseResponseAll);

  // {data} -> post "url" -> {data} / "html"
  exports.post = httpMethod('POST');

  // {data} -> post "url" -> {data} / "html"
  exports.put = httpMethod('PUT');

  // delete "url" -> ok
  exports.delete = httpMethod('DELETE');

  exports.tostring = function(inp, args, ctx, cb) {
    return cb(null, inp.toString());
  };

}).call(this);
