// Generated by CoffeeScript 2.7.0
(function() {
  var moment;

  moment = require('moment');

  exports['format-date'] = function(inp, args, ctx, cb) {
    return cb(null, moment(inp).format(args[0]));
  };

}).call(this);
