// Generated by CoffeeScript 1.11.1
(function() {
  var pm2, wrapall;

  pm2 = require('pm2');

  wrapall = require('hashpipe/helpers').wrapall;

  pm2.connect();

  module.exports = wrapall(pm2, 'pm2.');

}).call(this);
