// Generated by CoffeeScript 2.7.0
(function() {
  var redisClient;

  redisClient = require('redis').createClient;

  exports.connect = function(config) {
    var fns, redis_client;
    redis_client = redisClient((config != null ? config.port : void 0) || 6379, (config != null ? config.host : void 0) || 'localhost');
    return fns = {
      redis: function(inp, args, ctx, cb) {
        return redis_client[args[0]](...args.slice(1), function(err, ret) {
          return cb(null, ret);
        });
      }
    };
  };

}).call(this);
