// Generated by CoffeeScript 1.8.0
(function() {
  var redisClient,
    __slice = [].slice;

  redisClient = require('redis').createClient;

  exports.connect = function(config) {
    var fns, redis_client;
    redis_client = redisClient((config != null ? config.port : void 0) || 6379, (config != null ? config.host : void 0) || 'localhost');
    return fns = {
      redis: function(inp, args, ctx, cb) {
        return redis_client[args[0]].apply(redis_client, __slice.call(args.slice(1)).concat([function(err, ret) {
          return cb(null, ret);
        }]));
      }
    };
  };

}).call(this);
