// Generated by CoffeeScript 2.7.0
(function() {
  var _, cachedGetJson, chunk_length, consumer_key, default_args, default_limit, default_limit_per, dolog, feedFetchStream, fetchStream, getFavorites, getFollowings, getResource, getSongFavoriters, getTrack, getTracks, getUser, h, log, mapobjwith, qs, redis, request, resolve, resolveOne, searchTracks, searchUsers, shuffle, somata, util, wrapCallback, wrapStream;

  request = require('request');

  qs = require('querystring');

  h = require('highland');

  somata = require('somata');

  log = somata.helpers.log;

  util = require('util');

  redis = require('redis').createClient();

  _ = require('underscore');

  // Helper for logging with a [tag] prefix
  dolog = h.curry(function(t, s) {
    return log(`[${t}] ` + util.inspect(s).slice(0, 81).replace(/\s+/g, ' '));
  });

  // Fisher-Yates shuffling
  shuffle = function(a) {
    var i, j, l, ref;
    for (i = l = ref = a.length - 1; (ref <= 1 ? l <= 1 : l >= 1); i = ref <= 1 ? ++l : --l) {
      j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  };

  // API Fetching
  // ==============================================================================

  // Default SoundCloud API arguments
  consumer_key = "fc17d182cbdc4625d5a0b62322763759";

  default_args = {
    consumer_key: consumer_key,
    json: true
  };

  default_limit = 50;

  default_limit_per = 50;

  chunk_length = 50;

  // Try fetching URLs cached in Redis before going to the API
  cachedGetJson = function(options, cb) {
    var cache_key;
    // Save in redis as "cached:[url]"
    cache_key = 'cached:' + options.url;
    return redis.exists(cache_key, function(err, exists) {
      if (exists) {
        // Parse JSON right from redis if it exists
        return redis.get(cache_key, function(err, cached_string) {
          var cached;
          cached = JSON.parse(cached_string);
          return cb(null, cached);
        });
      } else {
        // Otherwise make the request
        return request.get(options, function(err, res, data_string) {
          var data;
          redis.set(cache_key, data_string); // Cache the results
          data = JSON.parse(data_string);
          return cb(null, data);
        });
      }
    });
  };

  // Create a stream of data fetched from the API
  fetchStream = function(path, args, limit = default_limit) {
    var stream;
    // Create a new stream and feed it
    stream = h();
    feedFetchStream(stream, path, args, limit);
    // Flatten (we're assuming arrays of data here) and enforce the limit with take
    return stream.flatten().take(limit);
  };

  // Feed an existing stream with data from the API
  feedFetchStream = function(stream, path, args, limit = default_limit, offset = 0) {
    var query_args, query_string, req_options, url;
    // Create the query string by extending default args with given args
    query_args = h.extend(default_args, {
      offset: offset,
      limit: default_limit_per
    });
    if (args != null) {
      query_args = h.extend(args, query_args);
    }
    query_string = qs.stringify(query_args);
    // Build the full URL
    url = `http://api.soundcloud.com/${path}.json?${query_string}`;
    req_options = {
      url: url
    };
    log(`[fetch] ${path}`);
    // Make the request (or get cached)
    cachedGetJson(req_options, function(err, data) {
      // Parse and feed the stream
      stream.write(data);
      if ((data.length === chunk_length) && (offset + chunk_length < limit)) {
        // Continue feeding if we haven't reached the end of the data or the limit of our results
        return feedFetchStream(stream, path, args, limit, offset + chunk_length);
      } else {
        // Close the stream if we're done
        return stream.end();
      }
    });
    return stream; // Return the stream for chainability
  };

  
  // Generic methods
  // ------------------------------------------------------------------------------

  // Resolve a Soundcloud URL
  resolve = function(url) {
    if (url.match(/http.*soundcloud\.com/) == null) {
      url = "http://soundcloud.com/" + url;
    }
    return fetchStream("resolve", {
      url: url
    });
  };

  //.doto(dolog "resolve #{ url }") # print each one
  resolveOne = function(url, cb) {
    return resolve(url).take(1).toArray(function([i]) {
      return cb(null, i);
    });
  };

  getResource = function(path) {
    return fetchStream(path);
  };

  getTrack = function(track) {
    return fetchStream(`tracks/${track.id}`);
  };

  getUser = function(user) {
    return fetchStream(`users/${user.id}`);
  };

  // User methods
  // ------------------------------------------------------------------------------

  // Get a users's followings
  getFollowings = function(user, limit = 10) {
    return fetchStream(`users/${user.id}/followings`, null, limit);
  };

  //.doto(dolog "getFollowings #{ user.id }") # print each one

  // Get a users's tracks
  getTracks = function(user, limit = 50) {
    return fetchStream(`users/${user.id}/tracks`, null, limit);
  };

  //.doto(dolog "getTracks #{ user.id }") # print each one

  // Get a users's favorites
  getFavorites = function(user, limit = 50) {
    return fetchStream(`users/${user.id}/favorites`, null, limit);
  };

  //.doto(dolog "getFavorites #{ user.id }") # print each one

  // Song methods
  // ------------------------------------------------------------------------------
  getSongFavoriters = function(song, limit = 50) {
    return fetchStream(`tracks/${song.id}/favoriters`, null, limit);
  };

  //.doto(dolog "getSongFavorites #{ song_id }") # print each one

  // Searches
  // ------------------------------------------------------------------------------
  searchTracks = function(query, limit = 50) {
    return fetchStream("tracks", {
      q: query
    }, limit);
  };

  //.doto(dolog "searchTracks #{ query }") # print each one
  searchUsers = function(query, limit = 50) {
    return fetchStream("users", {
      q: query
    }, limit);
  };

  //.doto(dolog "searchUsers #{ query }") # print each one

  // Export
  // ==============================================================================

  // Wrap stream methods as node-style callbacks for export
  wrapStream = function(method) {
    return function(inp, args, ctx, cb) {
      return method(...args).toArray(function(got) {
        return cb(null, got);
      });
    };
  };

  wrapCallback = function(method) {
    return function(inp, args, ctx, cb) {
      return method(...args, cb);
    };
  };

  // Return an object that applies f to every value of object o
  mapobjwith = function(f) {
    return function(o) {
      return _.object(_.pairs(o).map(function([k, v]) {
        return [k, f(v)];
      }));
    };
  };

  module.exports = _.extend({}, mapobjwith(wrapStream)({resolve, getResource, getTrack, getUser, getFollowings, getTracks, getFavorites, getSongFavoriters, searchTracks, searchUsers}), mapobjwith(wrapCallback)({resolveOne}));

  console.log(util.inspect(module.exports));

}).call(this);
