// Generated by CoffeeScript 2.7.0
(function() {
  var statistics;

  statistics = require('simple-statistics');

  exports.linreg = function(inp, args, ctx, cb) {
    return cb(null, statistics.linear_regression().data(inp).mb());
  };

}).call(this);
