// Generated by CoffeeScript 1.11.1
(function() {
  var xml2js;

  xml2js = require('xml2js');

  exports.xml2js = function(inp, args, ctx, cb) {
    var parser;
    parser = new xml2js.Parser();
    return parser.parseString(inp, cb);
  };

}).call(this);
