// Generated by CoffeeScript 2.7.0
(function() {
  var util, wrapone, wraponeSync;

  util = require('util');

  exports.prettyPrint = function(o) {
    if (typeof o === 'object') {
      return util.inspect(o, {
        depth: null,
        colors: true
      });
    } else {
      return `${o}`;
    }
  };

  exports.wrapone = wrapone = function(f, with_inp = false) {
    return function(inp, args, ctx, cb) {
      if (with_inp) {
        args.unshift(inp);
      }
      return f(...args, cb);
    };
  };

  exports.wraponeSync = wraponeSync = function(f, with_inp = false) {
    return function(inp, args, ctx, cb) {
      if (with_inp) {
        args.unshift(inp);
      }
      return cb(null, f(...args));
    };
  };

  exports.wrapall = function(o, pre = '', with_inp = false, sync = false) {
    var f, k, wo, wrapf;
    wo = {};
    for (k in o) {
      f = o[k];
      if (typeof f === 'function') {
        wrapf = sync ? wraponeSync : wrapone;
        wo[pre + k] = wrapf(f, with_inp);
      }
    }
    return wo;
  };

}).call(this);
