// Generated by CoffeeScript 1.11.1
(function() {
  var util, wrapone, wraponeSync,
    slice = [].slice;

  util = require('util');

  exports.prettyPrint = function(o) {
    if (typeof o === 'object') {
      return util.inspect(o, {
        depth: null,
        colors: true
      });
    } else {
      return "" + o;
    }
  };

  exports.wrapone = wrapone = function(f, with_inp) {
    if (with_inp == null) {
      with_inp = false;
    }
    return function(inp, args, ctx, cb) {
      if (with_inp) {
        args.unshift(inp);
      }
      return f.apply(null, slice.call(args).concat([cb]));
    };
  };

  exports.wraponeSync = wraponeSync = function(f, with_inp) {
    if (with_inp == null) {
      with_inp = false;
    }
    return function(inp, args, ctx, cb) {
      if (with_inp) {
        args.unshift(inp);
      }
      return cb(null, f.apply(null, args));
    };
  };

  exports.wrapall = function(o, pre, with_inp, sync) {
    var f, k, wo, wrapf;
    if (pre == null) {
      pre = '';
    }
    if (with_inp == null) {
      with_inp = false;
    }
    if (sync == null) {
      sync = false;
    }
    wo = {};
    for (k in o) {
      f = o[k];
      if (typeof f === 'function') {
        wrapf = sync ? wraponeSync : wrapone;
        wo[pre + k] = wrapf(f, with_inp);
      }
    }
    return wo;
  };

}).call(this);
