// Generated by CoffeeScript 2.7.0
(function() {
  var Context, DEBUG, Pipeline, Scope, _, _inspect, accessor, async, at, builtins, descendObj, doCmd, fs, grammar, inspect, mapInto, parsePipelines, recv_, runPipeline, runPipelines, splitArgs, through, util;

  grammar = require('./grammar');

  builtins = require('./builtins');

  async = require('async');

  fs = require('fs');

  util = require('util');

  _ = require('underscore');

  DEBUG = false;

  // Grab some tools before you dig in
  recv_ = function(t, s) {
    return console.log(`[${t.toUpperCase()}] ${s}`);
  };

  _inspect = function(o) {
    return util.inspect(o, {
      depth: null
    });
  };

  inspect = function(o) {
    return console.log(_inspect(o));
  };

  // Create a context that can be extended with `.use`
  Scope = class Scope {
    constructor(init = {}) {
      _.extend(this, init);
      return this;
    }

    // Set a value on the current scope
    set(t, k, v) {
      if (DEBUG) {
        console.log(`[Scope set] Setting ${t} ${k} to ${v}`);
      }
      if (this[t] == null) {
        this[t] = {};
      }
      this[t][k] = v;
      return this;
    }

    // Get a value from the current scope, falling back to parent scope
    get(t, k) {
      var got, ref, ref1;
      if (DEBUG) {
        console.log(`[Scope get] Getting ${t} ${k}`);
      }
      if (k != null) {
        got = (ref = this[t]) != null ? ref[k] : void 0;
      }
      if (k == null) {
        got = this[t];
      }
      return got || ((ref1 = this.parent) != null ? ref1.get(t, k) : void 0);
    }

    // Set an alias on the highest ranking scope
    alias(a, s) {
      if (this.parent != null) {
        return this.parent.alias(a, s);
      } else {
        this.set('fns', a, through(s));
        return this.set('aliases', a, s);
      }
    }

    // Create a new child scope for this scope
    subScope(init = {}) {
      init.parent = this;
      return new Scope(init);
    }

    topScope() {
      if (this.parent != null) {
        return this.parent.topScope();
      } else {
        return this;
      }
    }

  };

  Context = class Context extends Scope {};

  Pipeline = class Pipeline extends Scope {
    use(fns) {
      var k, ref, v;
      // Module name
      if (_.isString(fns)) {
        if (fns.match(/^\w/)) {
          fns = './modules/' + fns;
        }
        ref = require(fns);
        for (k in ref) {
          v = ref[k];
          this.set('fns', k, v);
        }
      // Object of functions
      } else if (_.isObject(fns)) {
        for (k in fns) {
          v = fns[k];
          this.set('fns', k, v);
        }
      }
      return this; // for chaining
    }

    
      // Execute a pipeline given a command string, input object,
    // context and callback. An empty context object is created
    // if none is given.

      // exec script, cb
    // exec script, inp, cb
    // exec script, inp, ctx, cb
    exec(script, inp, ctx, cb) {
      var e, pipelines;
      if (cb == null) {
        cb = ctx;
        ctx = this.subScope();
      }
      if (cb == null) {
        cb = inp;
        inp = null;
      }
      try {
        pipelines = parsePipelines(script);
      } catch (error) {
        e = error;
        cb("Error parsing pipeline: " + e);
      }
      try {
        runPipelines(pipelines, inp, ctx, cb);
      } catch (error) {
        e = error;
        cb("Error executing pipeline: " + e);
      }
      return ctx;
    }

    execFile(script_filename, inp, ctx, cb) {
      var script;
      script = fs.readFileSync(script_filename).toString();
      return this.exec(script, inp, ctx, cb);
    }

  };

  // Parse a command pipeline into a series of tokens
  // that can be passed to `runPipeline`
  parsePipelines = function(cmd) {
    return grammar.parse(cmd);
  };

  // Execute a parsed command pipeline, executing each part
  // recursively by setting a callback that is either the next
  // command in line or a final "stdout" callback

  //        /~+~+~+~+~+~+~+~+~+~+~+~+~+\
  //       |  PROCEED AT YOUR OWN RISK  |
  //       |       dragons afoot        |
  //        \+~+~+~+~+~+~+~+~+~+~+~+~+~/ 
  runPipelines = function(pipelines, inp, ctx, cb) {
    var _runPipeline;
    if (pipelines.length > 1) {
      _runPipeline = function(_pipeline, _cb) {
        return runPipeline(_pipeline, inp, ctx, _cb);
      };
      return async.mapSeries(pipelines, _runPipeline, function(err, results) {
        return cb(err, results.slice(-1)[0]);
      });
    } else {
      return runPipeline(pipelines[0], inp, ctx, cb);
    }
  };

  runPipeline = function(_cmd_tokens, inp, ctx, final_cb) {
    var $key, applyAt, cb, cmd_args, cmd_token, cmd_tokens, cmd_type, key, parseArgs, tasks, val;
    if (DEBUG) {
      console.log('\n=== RUNNING PIPELINE ===');
      inspect(inp);
      console.log(' ---> ');
      inspect(_cmd_tokens);
      console.log('========================\n');
    }
    cmd_tokens = _.clone(_cmd_tokens);
    cmd_token = cmd_tokens.shift();
    cmd_args = cmd_token.cmd;
    cmd_type = cmd_token.type;
    if (!cmd_args) {
      cmd_args = ['id'];
    }
    // Replace sub-commands and variables
    parseArgs = function(inp, args, cb) {
      var replaceArg;
      if (DEBUG) {
        console.log('parsing args for ' + _inspect(inp));
        console.log(':::> ' + _inspect(args));
      }
      if (cmd_args[0] === 'alias') {
        return cb(null, args);
      }
      replaceArg = function(arg, _cb) {
        var $key, key, val;
        if (_.isObject(arg)) {
          if (arg.sub != null) {
            return runPipelines(arg.sub, inp, ctx, _cb);
          } else if (arg.quoted != null) {
            return parseArgs(inp, arg.quoted, function(err, qargs) {
              return _cb(null, qargs.join(' '));
            });
          }
        } else if (_.isString(arg)) {
          // Int replacement
          if ($key = arg.match(/^-?[0-9]+$/)) {
            arg = parseInt(arg);
          // Non replacement (escaped)
          } else if ($key = arg.match(/\\\$[a-zA-Z0-9_-]*$/)) {
            arg = $key[0].slice(1);
          } else {
            // Within string replacement
            while ($key = arg.match(/\$[!a-zA-Z0-9_-]+/)) {
              $key = $key[0];
              if ($key === '$!') {
                val = inp;
              } else {
                key = $key.slice(1);
                val = ctx.get('vars', key);
              }
              arg = arg.replace($key, val);
            }
          }
        }
        return _cb(null, arg);
      };
      return async.map(args, replaceArg, function(err, new_args) {
        return cb(null, new_args);
      });
    };
    // Apply an at expression at the end
    applyAt = function(data, cb) {
      var _at;
      if (cmd_token.at != null) {
        if (cmd_type === 'ppipe' || cmd_type === 'spipe') {
          _at = function(_data, _cb) {
            return at(_data, cmd_token.at, ctx, _cb);
          };
          return async.map(data, _at, cb);
        } else {
          return at(data, cmd_token.at, ctx, cb);
        }
      } else {
        return cb(null, data);
      }
    };
    // Check if we're at the final step
    if (cmd_tokens.length === 0) {
      cb = function(err, ret) {
        if (DEBUG) {
          console.log(' ===> ' + _inspect(ret));
        }
        if (err) {
          return final_cb(err);
        } else {
          return applyAt(ret, final_cb);
        }
      };
    } else {
      // Create a callback to continue the pipeline otherwise
      cb = function(err, ret) {
        return applyAt(ret, function(err, ret) {
          return runPipeline(cmd_tokens, ret, ctx, final_cb);
        });
      };
    }
    // Parse arguments and then execute

    // Parallel if ppiped
    if (cmd_type === 'ppipe') {
      if (DEBUG) {
        console.log('PPIPE: ' + _inspect(cmd_args));
      }
      tasks = inp.map(function(_inp) {
        return function(_cb) {
          return parseArgs(_inp, cmd_args, function(err, args) {
            return doCmd(args, _inp, ctx, _cb);
          });
        };
      });
      return async.parallel(tasks, cb);
    // Series if spiped
    } else if (cmd_type === 'spipe') {
      if (DEBUG) {
        console.log('SPIPE: ' + _inspect(cmd_args));
      }
      tasks = inp.map(function(_inp) {
        return function(_cb) {
          return parseArgs(_inp, cmd_args, function(err, args) {
            return doCmd(args, _inp, ctx, _cb);
          });
        };
      });
      return async.series(tasks, cb);
    // Return literal value (number or string) if $val
    } else if (cmd_token.val != null) {
      if (DEBUG) {
        console.log('VAL: ' + _inspect(cmd_args));
      }
      return parseArgs(inp, [cmd_token.val], function(err, parsed) {
        return cb(null, parsed[0]);
      });
    // Return variable value if $var
    } else if (cmd_token.var != null) {
      if (DEBUG) {
        console.log('VAR: ' + _inspect(cmd_args));
      }
      $key = cmd_token.var;
      if ($key === '$!') {
        val = inp;
      } else {
        key = $key.slice(1);
        val = ctx.get('vars', key);
      }
      return cb(null, val);
    } else {
      if (DEBUG) {
        // Just execute if single piped
        console.log('PIPE: ' + _inspect(cmd_args));
      }
      return parseArgs(inp, cmd_args, function(err, args) {
        return doCmd(args, inp, ctx, cb);
      });
    }
  };

  // Execute a given command by looking in `ctx.fns` for a function
  // called `[cmd]` and passing that function the split arguments
  doCmd = function(_args, inp, ctx, cb) {
    var args, cmd, fn;
    if (DEBUG) {
      console.log('\n##### DO CMD ######');
      inspect(_args);
      inspect(inp);
      console.log('###################\n');
    }
    args = _.clone(_args);
    cmd = args.shift();
    if (fn = builtins[cmd]) {
      return fn(inp, args, ctx, cb);
    } else if (fn = ctx.get('fns', cmd)) {
      return fn(inp, args, ctx, cb);
    } else {
      return cb(`No command ${cmd}. `);
    }
  };

  // Splits a string into "arguments" by separating with whitespace
  // while attempting to treat quoted strings as single arguments.
  // TODO: Make a more robust grammar that can handle escaping, etc.
  splitArgs = function(s) {
    var args;
    args = [];
    s.trim().replace(/"([^"]*)"|'([^']*)'|(\S+)/g, function(g0, g1, g2, g3) {
      return args.push(g1 || g2 || g3 || '');
    });
    return args;
  };

  // Map a function into array of arrays at a certain depth
  mapInto = function(l, f, d, cb) {
    var _into;
    if (d === 1) {
      return async.map(l, f, cb);
    } else {
      _into = function(_l, _cb) {
        return mapInto(_l, f, d - 1, _cb);
      };
      return async.map(l, _into, cb);
    }
  };

  //   , \-._ >._,_     _,_.< _.-/
  //   (   )  \(-='(     )`--)/  (   _    
  //    `\-\_/-')\/'     `\/(`-\_/-/' `   
  //     <`)_--(_\_       _/_)--_('> 

  // Take an object and an expression and follow the expression
  // tree down to the desired result
  descendObj = function(_obj, _expr, ctx, final_cb) {
    var cb, expr, i, len, map_get, obj, ref, set, step, tasks;
    if (_obj == null) {
      return final_cb(null, void 0);
    }
    // This is me hoping Node has really good GC
    obj = _.clone(_obj);
    expr = _.clone(_expr);
    step = expr.shift();
    if (DEBUG) {
      console.log("\n/ - - ~ @ ~ - - \\");
      inspect(obj);
      console.log("      == @ ==> ");
      inspect(step);
      console.log("\\ - - ~ @ ~ - - /\n");
    }
    // Check if we're at the final step
    if (expr.length === 0) {
      cb = final_cb;
    } else {
      cb = function(err, ret) {
        return descendObj(ret, expr, ctx, final_cb);
      };
    }
    if (step == null) {
      cb(null, obj);
    }
    // Map attributes
    if (step.map != null) {
      map_get = function(__obj, _cb) {
        return descendObj(__obj, [
          {
            get: step.map
          }
        ], ctx, _cb);
      };
      return mapInto(obj, map_get, step.depth, cb);
    // Substitution
    } else if (step.sub != null) {
      return runPipelines(step.sub, obj, ctx, cb);
    // Array result
    } else if (_.isArray(step.get)) {
      tasks = step.get.map(function(step_expr) {
        return function(_cb) {
          return descendObj(obj, step_expr, ctx, _cb);
        };
      });
      return async.parallel(tasks, cb);
    // Object result
    } else if (_.isObject(step.get) && (step.get.obj != null)) {
      tasks = [];
      ref = step.get.obj;
      for (i = 0, len = ref.length; i < len; i++) {
        set = ref[i];
        (function(set) {
          var e, k;
          k = set.key;
          e = set.val;
          if (_.isString(k)) {
            // Key is a string, just get value
            return tasks.push(function(_cb) {
              // Check if value is a sub-command or an at-expression
              if (e.sub != null) {
                return runPipelines(e.sub, obj, ctx, function(err, v_obj) {
                  var dobj;
                  dobj = {
                    key: k,
                    val: v_obj
                  };
                  return _cb(null, dobj);
                });
              } else {
                return descendObj(obj, e, ctx, function(err, v_obj) {
                  var dobj;
                  dobj = {
                    key: k,
                    val: v_obj
                  };
                  return _cb(null, dobj);
                });
              }
            });
          } else {
            // Key is an expression, get both key value and value value
            return tasks.push(function(_cb) {
              return descendObj(obj, k, ctx, function(err, k_obj) {
                // Check if value is a sub-command or an at-expression
                if (e.sub != null) {
                  return runPipelines(e.sub, obj, ctx, function(err, v_obj) {
                    var dobj;
                    dobj = {
                      key: k_obj,
                      val: v_obj
                    };
                    return _cb(null, dobj);
                  });
                } else {
                  return descendObj(obj, e, ctx, function(err, v_obj) {
                    var dobj;
                    dobj = {
                      key: k_obj,
                      val: v_obj
                    };
                    return _cb(null, dobj);
                  });
                }
              });
            });
          }
        })(set);
      }
      // Combine results into single object
      return async.parallel(tasks, function(err, results) {
        var j, len1, result, result_obj;
        result_obj = {};
        for (j = 0, len1 = results.length; j < len1; j++) {
          result = results[j];
          result_obj[result.key] = result.val;
        }
        return cb(null, result_obj);
      });
    } else {
      // Get attribute
      return cb(null, accessor(obj, step.get));
    }
  };

  accessor = function(obj, key) {
    if (key === '.') {
      return obj;
    } else {
      if (key.match(/^-?\d+/)) {
        key = Number(key);
        // Pythonesque negative indexes
        if (key < 0) {
          return obj.slice(key)[0];
        }
      }
      return obj[key];
    }
  };

  // create a command out of a script
  through = function(cmd) {
    return function(inp, args, ctx, cb) {
      var pipeline;
      pipeline = parsePipelines(cmd)[0];
      if (pipeline[0].cmd != null) {
        pipeline[0].cmd.push(...args);
      }
      return runPipeline(pipeline, inp, ctx, cb);
    };
  };

  // Read in an at expression
  at = function(inp, expr, ctx, cb) {
    return descendObj(inp, expr, ctx, cb);
  };

  module.exports = {
    Pipeline: Pipeline,
    Context: Context,
    parsePipelines: parsePipelines,
    runPipeline: runPipeline,
    doCmd: doCmd,
    through: through,
    at: at
  };

}).call(this);
