// Generated by CoffeeScript 1.8.0
(function() {
  var expected_result, expr, inspect, pipeline, tape, test_input, util, _inspect;

  pipeline = require('../pipeline');

  tape = require('tape');

  util = require('util');

  _inspect = function(o) {
    return util.inspect(o, {
      depth: null
    });
  };

  inspect = function(o) {
    return console.log(_inspect(o));
  };

  test_input = {
    name: 'jones',
    favorites: {
      animal: 'walrus',
      color: 'chartreuse'
    },
    things: [
      [
        {
          name: 'james',
          type: 'friend'
        }, {
          name: 'joe',
          type: 'friend'
        }
      ], [
        {
          name: 'apple',
          type: 'food'
        }
      ]
    ]
  };

  expr = [
    {
      get: 'things'
    }, {
      map: 'type',
      depth: 2
    }
  ];

  expected_result = [['friend', 'friend'], ['food']];

  tape('descend_test', function(t) {
    return pipeline.at(test_input, expr, {}, function(err, test_result) {
      t.deepLooseEqual(test_result, expected_result, 'Meets expectations.');
      return t.end();
    });
  });

}).call(this);
